import { type Metadata } from "next";
import { Inter } from "next/font/google";
import Head from "next/head";

import { ColorSchemeScript, MantineProvider } from "@mantine/core";
import "@mantine/core/styles.layer.css";
import "@mantine/dates/styles.layer.css";
import { Notifications } from "@mantine/notifications";
import "@mantine/notifications/styles.layer.css";

import "mantine-datatable/styles.layer.css";
import NextTopLoader from "nextjs-toploader";

import { ReactQueryClientProvider } from "@/providers/ReactQueryClientProvider";
import { theme } from "@/theme";

import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const inter = Inter({ subsets: ["latin"] });

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <Head>
        <ColorSchemeScript />
      </Head>

      <body className={inter.className}>
        <MantineProvider theme={theme}>
          <NextTopLoader showSpinner={false} />
          <Notifications position="top-right" />
          <ReactQueryClientProvider>{children}</ReactQueryClientProvider>
        </MantineProvider>
      </body>
    </html>
  );
}
