import { type Metadata } from "next";
import { Inter } from "next/font/google";

import { ColorSchemeScript, MantineProvider } from "@mantine/core";
import "@mantine/core/styles.layer.css";
import "@mantine/dates/styles.layer.css";
import { Notifications } from "@mantine/notifications";
import "@mantine/notifications/styles.layer.css";
import "@mantine/nprogress/styles.layer.css";

import { AuthProvider } from "@/providers/AuthProvider";
import QueryClientProvider from "@/providers/QueryClientProvider";
import { theme } from "@/theme";

import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const inter = Inter({ subsets: ["latin"] });

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ColorSchemeScript />
        <MantineProvider theme={theme}>
          <AuthProvider>
            <QueryClientProvider>
              <Notifications position="top-right" />
              {children}
            </QueryClientProvider>
          </AuthProvider>
        </MantineProvider>
      </body>
    </html>
  );
}
